### ISSUE TITLE
CMakeLists configuration file support detection

### ISSUE THREAD

**Issue by niliopoulos** [michele-segata/mpclib#2]
The line:
`if (${LIBCONFIGPP_FOUND} AND ${MATHEVAL_FOUND})`

needs to change to:

```
if (LIBCONFIGPP_FOUND AND MATHEVAL_FOUND)
        message(STATUS "Found libconfig++ and matheval: enabling configuration file support")
```
to enable boolean operations because currently the expression arguments are parsed as strings. This confuses cmake when any of the two libs is not installed since the strings may not be set.

**Comment by michele-segata** [comment]
Thanks. Fixed in https://github.com/michele-segata/mpclib/commit/90dd6e1767e65a2cfa708eeb2f3a96d6ff989b8b
